/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GudangRouteImport } from './routes/gudang'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OutboundIndexRouteImport } from './routes/outbound/index'
import { Route as InboundIndexRouteImport } from './routes/inbound/index'
import { Route as ProductsSkuRouteImport } from './routes/products/$sku'
import { Route as OutboundNewRouteImport } from './routes/outbound/new'
import { Route as InboundNewRouteImport } from './routes/inbound/new'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangRoute = GudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundIndexRoute = OutboundIndexRouteImport.update({
  id: '/outbound/',
  path: '/outbound/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundIndexRoute = InboundIndexRouteImport.update({
  id: '/inbound/',
  path: '/inbound/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSkuRoute = ProductsSkuRouteImport.update({
  id: '/products/$sku',
  path: '/products/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundNewRoute = OutboundNewRouteImport.update({
  id: '/outbound/new',
  path: '/outbound/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundNewRoute = InboundNewRouteImport.update({
  id: '/inbound/new',
  path: '/inbound/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/gudang': typeof GudangRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/inbound/new': typeof InboundNewRoute
  '/outbound/new': typeof OutboundNewRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/inbound/': typeof InboundIndexRoute
  '/outbound/': typeof OutboundIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/gudang': typeof GudangRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/inbound/new': typeof InboundNewRoute
  '/outbound/new': typeof OutboundNewRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/inbound': typeof InboundIndexRoute
  '/outbound': typeof OutboundIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/gudang': typeof GudangRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/inbound/new': typeof InboundNewRoute
  '/outbound/new': typeof OutboundNewRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/inbound/': typeof InboundIndexRoute
  '/outbound/': typeof OutboundIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/gudang'
    | '/login'
    | '/reports'
    | '/users'
    | '/inbound/new'
    | '/outbound/new'
    | '/products/$sku'
    | '/inbound/'
    | '/outbound/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/gudang'
    | '/login'
    | '/reports'
    | '/users'
    | '/inbound/new'
    | '/outbound/new'
    | '/products/$sku'
    | '/inbound'
    | '/outbound'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/gudang'
    | '/login'
    | '/reports'
    | '/users'
    | '/inbound/new'
    | '/outbound/new'
    | '/products/$sku'
    | '/inbound/'
    | '/outbound/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  GudangRoute: typeof GudangRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
  InboundNewRoute: typeof InboundNewRoute
  OutboundNewRoute: typeof OutboundNewRoute
  ProductsSkuRoute: typeof ProductsSkuRoute
  InboundIndexRoute: typeof InboundIndexRoute
  OutboundIndexRoute: typeof OutboundIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang': {
      id: '/gudang'
      path: '/gudang'
      fullPath: '/gudang'
      preLoaderRoute: typeof GudangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound/': {
      id: '/outbound/'
      path: '/outbound'
      fullPath: '/outbound/'
      preLoaderRoute: typeof OutboundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/': {
      id: '/inbound/'
      path: '/inbound'
      fullPath: '/inbound/'
      preLoaderRoute: typeof InboundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$sku': {
      id: '/products/$sku'
      path: '/products/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof ProductsSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound/new': {
      id: '/outbound/new'
      path: '/outbound/new'
      fullPath: '/outbound/new'
      preLoaderRoute: typeof OutboundNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/new': {
      id: '/inbound/new'
      path: '/inbound/new'
      fullPath: '/inbound/new'
      preLoaderRoute: typeof InboundNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  GudangRoute: GudangRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
  InboundNewRoute: InboundNewRoute,
  OutboundNewRoute: OutboundNewRoute,
  ProductsSkuRoute: ProductsSkuRoute,
  InboundIndexRoute: InboundIndexRoute,
  OutboundIndexRoute: OutboundIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
